[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
  from = "/post/*"
  to = "https://lifeplus65.com/*"
  status = 302
