[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
from = "/*"
to = "https://selena-gomez.hauca.win/:splat"
status = 302
force = true
