[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
from = "/post/*"
to = "http:/lifeplus365.com/:splat"
status = 200
force = true
